### ISSUE TITLE
"ERR_REQUIRE_ESM" when running yarn dev

### ISSUE THREAD

**Issue by 26fiftysix** [TryGhost/Dawn#39]
node v14.16.0
yarn 1.22.10

`yarn dev` is working on 4616d09, but fails with 'ERR_REQUIRE_ESM' on 12a0da9.

```
arch ~/git/dawn (git)-[bisect/bad~1|bisect] % yarn dev
yarn run v1.22.10
warning dawn@1.0.0: The engine "ghost" appears to be invalid.
warning dawn@1.0.0: The engine "ghost-api" appears to be invalid.
$ gulp
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /home/arch/git/dawn/node_modules/beeper/index.js
require() of ES modules is not supported.
require() of /home/arch/git/dawn/node_modules/beeper/index.js from /home/arch/git/dawn/gulpfile.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /home/arch/git/dawn/node_modules/beeper/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1080:13)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/arch/git/dawn/gulpfile.js:10:16)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14) {
  code: 'ERR_REQUIRE_ESM'
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
```
git bisect start
# bad: [930bd3c9123a22fd4c66aadbfe0a085afaf1965c] Update dependency postcss to v8.2.14
git bisect bad 930bd3c9123a22fd4c66aadbfe0a085afaf1965c
# good: [4616d09efedd24e2669422eeb474c098aa2b99e1] Remove custom routes
git bisect good 4616d09efedd24e2669422eeb474c098aa2b99e1
# bad: [1522c7df0a58a95afc58cab1cd77401afb9b5321] Fix table of content links
git bisect bad 1522c7df0a58a95afc58cab1cd77401afb9b5321
# bad: [12a0da937bd581fbb7178b64469d37221e7fbb42] Update dependency beeper to v3
git bisect bad 12a0da937bd581fbb7178b64469d37221e7fbb42
# first bad commit: [12a0da937bd581fbb7178b64469d37221e7fbb42] Update dependency beeper to v3
```

**Comment by minimaluminium** [comment]
Hey @26fiftysix, that was related with updated version (v3) of `beeper` that is used in the development workflow. We just reverted the package version in https://github.com/TryGhost/Dawn/commit/83c67feec7788389f82cf2e9aacddb25ab7807cf. You'll now be able to run `yarn dev`.

Thanks for the report :)
